In [1]:
import pandas as pd

In [31]:
df1 = pd.read_csv('C:\\Users\\004NQ8744\\OneDrive\\Roadwork\\manpowergroup\\text2sqlbot\\data\\employee_data.csv')
df2 = pd.read_csv('C:\\Users\\004NQ8744\\OneDrive\\Roadwork\\manpowergroup\\text2sqlbot\\data\\employee_engagement_survey_data.csv')
df3 = pd.read_csv('C:\\Users\\004NQ8744\\OneDrive\\Roadwork\\manpowergroup\\text2sqlbot\\data\\training_and_development_data.csv')

In [32]:
df1.head()

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3

In [33]:
df2.head()

,Employee ID,Survey Date,Engagement Score,Satisfaction Score,Work-Life Balance Score
0,1001,10-10-2022,2,5,5
1,1002,03-08-2023,4,5,3
2,1003,03-01-2023,2,5,2
3,1004,30-07-2023,3,5,3
4,1005,19-06-2023,2,4,5

In [34]:
df1.columns

Index(['EmpID', 'FirstName', 'LastName', 'StartDate', 'ExitDate', 'Title',
       'Supervisor', 'ADEmail', 'BusinessUnit', 'EmployeeStatus',
       'EmployeeType', 'PayZone', 'EmployeeClassificationType',
       'TerminationType', 'TerminationDescription', 'DepartmentType',
       'Division', 'DOB', 'State', 'JobFunctionDescription', 'GenderCode',
       'LocationCode', 'RaceDesc', 'MaritalDesc', 'Performance Score',
       'Current Employee Rating'],
      dtype='str')

In [35]:
df2.columns

Index(['Employee ID', 'Survey Date', 'Engagement Score', 'Satisfaction Score',
       'Work-Life Balance Score'],
      dtype='str')

In [36]:
df3.columns

Index(['Employee ID', 'Training Date', 'Training Program Name',
       'Training Type', 'Training Outcome', 'Location', 'Trainer',
       'Training Duration(Days)', 'Training Cost'],
      dtype='str')

In [16]:
import re

In [21]:
"Employee_Data#1.csv".rsplit(".", 1)[0].lower().strip()

'employee_data#1'

In [22]:
re.sub(r"[^a-z0-9_]", "_", 'employee_data1')

'employee_data1'

In [30]:
re.sub(r"_+", "_", "0__employee___________data1").strip("_")

'0_employee_data1'

In [29]:
name = '0_employee_data1'
if name and name[0].isdigit():
    name = "t_" + name
name

't_0_employee_data1'